// <auto-generated/>
namespace PetStoreAl.models;

/// <summary>Order Status</summary>
enum 50002 Order_status
{

    value(0; "Placed")
    {
        Caption = 'placed', Locked = true;
    }
    value(1; "Approved")
    {
        Caption = 'approved', Locked = true;
    }
    value(2; "Delivered")
    {
        Caption = 'delivered', Locked = true;
    }
}
