// <auto-generated/>
namespace PetStoreAl.models;

/// <summary>pet status in the store</summary>
enum 50003 Pet_status
{
    Access = Internal;

    value(0; "Available")
    {
        Caption = 'available', Locked = true;
    }
    value(1; "Pending")
    {
        Caption = 'pending', Locked = true;
    }
    value(2; "Sold")
    {
        Caption = 'sold', Locked = true;
    }
}
