// <auto-generated/>
namespace PetStoreAl.pet.findByStatus;

enum 50001 GetStatusQueryParameterType
{

    value(0; "Available")
    {
        Caption = 'available', Locked = true;
    }
    value(1; "Pending")
    {
        Caption = 'pending', Locked = true;
    }
    value(2; "Sold")
    {
        Caption = 'sold', Locked = true;
    }
}
